import { Router, type IRouter } from "express";
import healthRouter from "./health";
import offersRouter from "./offers";
import destinationsRouter from "./destinations";
import programsRouter from "./programs";
import visasRouter from "./visas";
import visaCountriesRouter from "./visaCountries";
import visaCustomFieldsRouter from "./visaCustomFields";
import visaApplicationsRouter from "./visaApplications";
import umrahApplicationsRouter from "./umrahApplications";
import applicationDocumentsRouter from "./applicationDocuments";
import storageRouter from "./storage";
import bookingsRouter from "./bookings";
import contactRouter from "./contact";
import dashboardRouter from "./dashboard";
import authRouter from "./auth";
import flightsRouter from "./flights";
import notificationsRouter from "./notifications";
import employeesRouter from "./employees";
import settingsRouter from "./settings";
import auditLogsRouter from "./auditLogs";
import pushTokensRouter from "./pushTokens";
import supportChatRouter from "./supportChat";
import agenciesRouter from "./agencies";
import agentRouter from "./agent";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(flightsRouter);
router.use(offersRouter);
router.use(destinationsRouter);
router.use(programsRouter);
router.use(visaCountriesRouter);
router.use(visaCustomFieldsRouter);
router.use(visasRouter);
router.use(visaApplicationsRouter);
router.use(umrahApplicationsRouter);
router.use(applicationDocumentsRouter);
router.use(storageRouter);
router.use(bookingsRouter);
router.use(contactRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use(pushTokensRouter);
router.use(employeesRouter);
router.use(settingsRouter);
router.use(auditLogsRouter);
router.use(supportChatRouter);
router.use(agenciesRouter);
router.use(agentRouter);

export default router;
