/**
 * nationalities.ts — جميع جنسيات العالم مرتبة أبجدياً بالعربية
 * كل عنصر: { code: ISO-3166-1 alpha-2, nameAr, demonymAr, flag }
 */
export interface Nationality {
  code: string;
  nameAr: string;      // اسم الدولة
  demonymAr: string;   // وصف الجنسية (يُدخله المستخدم)
  flag: string;
}

export const NATIONALITIES: Nationality[] = [
  { code: 'AF', nameAr: 'أفغانستان',                demonymAr: 'أفغاني',           flag: '🇦🇫' },
  { code: 'AL', nameAr: 'ألبانيا',                   demonymAr: 'ألباني',           flag: '🇦🇱' },
  { code: 'DZ', nameAr: 'الجزائر',                   demonymAr: 'جزائري',           flag: '🇩🇿' },
  { code: 'AD', nameAr: 'أندورا',                    demonymAr: 'أندوري',           flag: '🇦🇩' },
  { code: 'AO', nameAr: 'أنغولا',                    demonymAr: 'أنغولي',           flag: '🇦🇴' },
  { code: 'AG', nameAr: 'أنتيغوا وبربودا',           demonymAr: 'أنتيغوي',          flag: '🇦🇬' },
  { code: 'AR', nameAr: 'الأرجنتين',                 demonymAr: 'أرجنتيني',         flag: '🇦🇷' },
  { code: 'AM', nameAr: 'أرمينيا',                   demonymAr: 'أرمني',            flag: '🇦🇲' },
  { code: 'AU', nameAr: 'أستراليا',                  demonymAr: 'أسترالي',          flag: '🇦🇺' },
  { code: 'AT', nameAr: 'النمسا',                    demonymAr: 'نمساوي',           flag: '🇦🇹' },
  { code: 'AZ', nameAr: 'أذربيجان',                  demonymAr: 'أذربيجاني',        flag: '🇦🇿' },
  { code: 'BS', nameAr: 'جزر البهاما',               demonymAr: 'باهامي',           flag: '🇧🇸' },
  { code: 'BH', nameAr: 'البحرين',                   demonymAr: 'بحريني',           flag: '🇧🇭' },
  { code: 'BD', nameAr: 'بنغلاديش',                  demonymAr: 'بنغلاديشي',        flag: '🇧🇩' },
  { code: 'BB', nameAr: 'بربادوس',                   demonymAr: 'بربادوسي',         flag: '🇧🇧' },
  { code: 'BY', nameAr: 'بيلاروسيا',                 demonymAr: 'بيلاروسي',         flag: '🇧🇾' },
  { code: 'BE', nameAr: 'بلجيكا',                    demonymAr: 'بلجيكي',           flag: '🇧🇪' },
  { code: 'BZ', nameAr: 'بليز',                      demonymAr: 'بليزي',            flag: '🇧🇿' },
  { code: 'BJ', nameAr: 'بنين',                      demonymAr: 'بنيني',            flag: '🇧🇯' },
  { code: 'BT', nameAr: 'بوتان',                     demonymAr: 'بوتاني',           flag: '🇧🇹' },
  { code: 'BO', nameAr: 'بوليفيا',                   demonymAr: 'بوليفي',           flag: '🇧🇴' },
  { code: 'BA', nameAr: 'البوسنة والهرسك',            demonymAr: 'بوسني',            flag: '🇧🇦' },
  { code: 'BW', nameAr: 'بوتسوانا',                  demonymAr: 'بوتسواني',         flag: '🇧🇼' },
  { code: 'BR', nameAr: 'البرازيل',                  demonymAr: 'برازيلي',          flag: '🇧🇷' },
  { code: 'BN', nameAr: 'بروناي',                    demonymAr: 'بروناوي',          flag: '🇧🇳' },
  { code: 'BG', nameAr: 'بلغاريا',                   demonymAr: 'بلغاري',           flag: '🇧🇬' },
  { code: 'BF', nameAr: 'بوركينا فاسو',              demonymAr: 'بوركيني',          flag: '🇧🇫' },
  { code: 'BI', nameAr: 'بوروندي',                   demonymAr: 'بوروندي',          flag: '🇧🇮' },
  { code: 'CV', nameAr: 'الرأس الأخضر',              demonymAr: 'كابوفيردي',        flag: '🇨🇻' },
  { code: 'KH', nameAr: 'كمبوديا',                   demonymAr: 'كمبودي',           flag: '🇰🇭' },
  { code: 'CM', nameAr: 'الكاميرون',                 demonymAr: 'كاميروني',         flag: '🇨🇲' },
  { code: 'CA', nameAr: 'كندا',                      demonymAr: 'كندي',             flag: '🇨🇦' },
  { code: 'CF', nameAr: 'جمهورية أفريقيا الوسطى',   demonymAr: 'أفريقي أوسطي',    flag: '🇨🇫' },
  { code: 'TD', nameAr: 'تشاد',                      demonymAr: 'تشادي',            flag: '🇹🇩' },
  { code: 'CL', nameAr: 'تشيلي',                     demonymAr: 'تشيلي',            flag: '🇨🇱' },
  { code: 'CN', nameAr: 'الصين',                     demonymAr: 'صيني',             flag: '🇨🇳' },
  { code: 'CO', nameAr: 'كولومبيا',                  demonymAr: 'كولومبي',          flag: '🇨🇴' },
  { code: 'KM', nameAr: 'جزر القمر',                 demonymAr: 'قمري',             flag: '🇰🇲' },
  { code: 'CG', nameAr: 'الكونغو',                   demonymAr: 'كونغولي',          flag: '🇨🇬' },
  { code: 'CD', nameAr: 'الكونغو الديمقراطية',       demonymAr: 'كونغولي ديمقراطي', flag: '🇨🇩' },
  { code: 'CR', nameAr: 'كوستاريكا',                 demonymAr: 'كوستاريكي',        flag: '🇨🇷' },
  { code: 'CI', nameAr: 'ساحل العاج',                demonymAr: 'إيفواري',          flag: '🇨🇮' },
  { code: 'HR', nameAr: 'كرواتيا',                   demonymAr: 'كرواتي',           flag: '🇭🇷' },
  { code: 'CU', nameAr: 'كوبا',                      demonymAr: 'كوبي',             flag: '🇨🇺' },
  { code: 'CY', nameAr: 'قبرص',                      demonymAr: 'قبرصي',            flag: '🇨🇾' },
  { code: 'CZ', nameAr: 'التشيك',                    demonymAr: 'تشيكي',            flag: '🇨🇿' },
  { code: 'DK', nameAr: 'الدنمارك',                  demonymAr: 'دنماركي',          flag: '🇩🇰' },
  { code: 'DJ', nameAr: 'جيبوتي',                    demonymAr: 'جيبوتي',           flag: '🇩🇯' },
  { code: 'DM', nameAr: 'دومينيكا',                  demonymAr: 'دومينيكي',         flag: '🇩🇲' },
  { code: 'DO', nameAr: 'جمهورية الدومينيكان',       demonymAr: 'دومينيكاني',       flag: '🇩🇴' },
  { code: 'EC', nameAr: 'الإكوادور',                 demonymAr: 'إكوادوري',         flag: '🇪🇨' },
  { code: 'EG', nameAr: 'مصر',                       demonymAr: 'مصري',             flag: '🇪🇬' },
  { code: 'SV', nameAr: 'السلفادور',                 demonymAr: 'سلفادوري',         flag: '🇸🇻' },
  { code: 'GQ', nameAr: 'غينيا الاستوائية',          demonymAr: 'غيني استوائي',     flag: '🇬🇶' },
  { code: 'ER', nameAr: 'إريتريا',                   demonymAr: 'إريتري',           flag: '🇪🇷' },
  { code: 'EE', nameAr: 'إستونيا',                   demonymAr: 'إستوني',           flag: '🇪🇪' },
  { code: 'SZ', nameAr: 'إسواتيني',                  demonymAr: 'إسواتيني',         flag: '🇸🇿' },
  { code: 'ET', nameAr: 'إثيوبيا',                   demonymAr: 'إثيوبي',           flag: '🇪🇹' },
  { code: 'FJ', nameAr: 'فيجي',                      demonymAr: 'فيجي',             flag: '🇫🇯' },
  { code: 'FI', nameAr: 'فنلندا',                    demonymAr: 'فنلندي',           flag: '🇫🇮' },
  { code: 'FR', nameAr: 'فرنسا',                     demonymAr: 'فرنسي',            flag: '🇫🇷' },
  { code: 'GA', nameAr: 'الغابون',                   demonymAr: 'غابوني',           flag: '🇬🇦' },
  { code: 'GM', nameAr: 'غامبيا',                    demonymAr: 'غامبي',            flag: '🇬🇲' },
  { code: 'GE', nameAr: 'جورجيا',                    demonymAr: 'جورجي',            flag: '🇬🇪' },
  { code: 'DE', nameAr: 'ألمانيا',                   demonymAr: 'ألماني',           flag: '🇩🇪' },
  { code: 'GH', nameAr: 'غانا',                      demonymAr: 'غاني',             flag: '🇬🇭' },
  { code: 'GR', nameAr: 'اليونان',                   demonymAr: 'يوناني',           flag: '🇬🇷' },
  { code: 'GD', nameAr: 'غرينادا',                   demonymAr: 'غرينادي',          flag: '🇬🇩' },
  { code: 'GT', nameAr: 'غواتيمالا',                 demonymAr: 'غواتيمالي',        flag: '🇬🇹' },
  { code: 'GN', nameAr: 'غينيا',                     demonymAr: 'غيني',             flag: '🇬🇳' },
  { code: 'GW', nameAr: 'غينيا بيساو',               demonymAr: 'غيني بيساوي',      flag: '🇬🇼' },
  { code: 'GY', nameAr: 'غيانا',                     demonymAr: 'غياني',            flag: '🇬🇾' },
  { code: 'HT', nameAr: 'هايتي',                     demonymAr: 'هايتي',            flag: '🇭🇹' },
  { code: 'HN', nameAr: 'هندوراس',                   demonymAr: 'هندوراسي',         flag: '🇭🇳' },
  { code: 'HU', nameAr: 'المجر',                     demonymAr: 'مجري',             flag: '🇭🇺' },
  { code: 'IS', nameAr: 'آيسلندا',                   demonymAr: 'آيسلندي',          flag: '🇮🇸' },
  { code: 'IN', nameAr: 'الهند',                     demonymAr: 'هندي',             flag: '🇮🇳' },
  { code: 'ID', nameAr: 'إندونيسيا',                 demonymAr: 'إندونيسي',         flag: '🇮🇩' },
  { code: 'IR', nameAr: 'إيران',                     demonymAr: 'إيراني',           flag: '🇮🇷' },
  { code: 'IQ', nameAr: 'العراق',                    demonymAr: 'عراقي',            flag: '🇮🇶' },
  { code: 'IE', nameAr: 'إيرلندا',                   demonymAr: 'إيرلندي',          flag: '🇮🇪' },
  { code: 'IL', nameAr: 'إسرائيل',                   demonymAr: 'إسرائيلي',         flag: '🇮🇱' },
  { code: 'IT', nameAr: 'إيطاليا',                   demonymAr: 'إيطالي',           flag: '🇮🇹' },
  { code: 'JM', nameAr: 'جامايكا',                   demonymAr: 'جامايكي',          flag: '🇯🇲' },
  { code: 'JP', nameAr: 'اليابان',                   demonymAr: 'ياباني',           flag: '🇯🇵' },
  { code: 'JO', nameAr: 'الأردن',                    demonymAr: 'أردني',            flag: '🇯🇴' },
  { code: 'KZ', nameAr: 'كازاخستان',                 demonymAr: 'كازاخستاني',       flag: '🇰🇿' },
  { code: 'KE', nameAr: 'كينيا',                     demonymAr: 'كيني',             flag: '🇰🇪' },
  { code: 'KI', nameAr: 'كيريباتي',                  demonymAr: 'كيريباتي',         flag: '🇰🇮' },
  { code: 'KP', nameAr: 'كوريا الشمالية',            demonymAr: 'كوري شمالي',       flag: '🇰🇵' },
  { code: 'KR', nameAr: 'كوريا الجنوبية',            demonymAr: 'كوري جنوبي',       flag: '🇰🇷' },
  { code: 'KW', nameAr: 'الكويت',                    demonymAr: 'كويتي',            flag: '🇰🇼' },
  { code: 'KG', nameAr: 'قيرغيزستان',                demonymAr: 'قيرغيزي',          flag: '🇰🇬' },
  { code: 'LA', nameAr: 'لاوس',                      demonymAr: 'لاوسي',            flag: '🇱🇦' },
  { code: 'LV', nameAr: 'لاتفيا',                    demonymAr: 'لاتفي',            flag: '🇱🇻' },
  { code: 'LB', nameAr: 'لبنان',                     demonymAr: 'لبناني',           flag: '🇱🇧' },
  { code: 'LS', nameAr: 'ليسوتو',                    demonymAr: 'ليسوتي',           flag: '🇱🇸' },
  { code: 'LR', nameAr: 'ليبيريا',                   demonymAr: 'ليبيري',           flag: '🇱🇷' },
  { code: 'LY', nameAr: 'ليبيا',                     demonymAr: 'ليبي',             flag: '🇱🇾' },
  { code: 'LI', nameAr: 'ليختنشتاين',                demonymAr: 'ليختنشتايني',      flag: '🇱🇮' },
  { code: 'LT', nameAr: 'ليتوانيا',                  demonymAr: 'ليتواني',          flag: '🇱🇹' },
  { code: 'LU', nameAr: 'لوكسمبورغ',                 demonymAr: 'لوكسمبورغي',       flag: '🇱🇺' },
  { code: 'MG', nameAr: 'مدغشقر',                    demonymAr: 'مدغشقري',          flag: '🇲🇬' },
  { code: 'MW', nameAr: 'ملاوي',                     demonymAr: 'ملاوي',            flag: '🇲🇼' },
  { code: 'MY', nameAr: 'ماليزيا',                   demonymAr: 'ماليزي',           flag: '🇲🇾' },
  { code: 'MV', nameAr: 'المالديف',                  demonymAr: 'مالديفي',          flag: '🇲🇻' },
  { code: 'ML', nameAr: 'مالي',                      demonymAr: 'مالي',             flag: '🇲🇱' },
  { code: 'MT', nameAr: 'مالطا',                     demonymAr: 'مالطي',            flag: '🇲🇹' },
  { code: 'MH', nameAr: 'جزر مارشال',                demonymAr: 'مارشالي',          flag: '🇲🇭' },
  { code: 'MR', nameAr: 'موريتانيا',                 demonymAr: 'موريتاني',         flag: '🇲🇷' },
  { code: 'MU', nameAr: 'موريشيوس',                  demonymAr: 'موريشيوسي',        flag: '🇲🇺' },
  { code: 'MX', nameAr: 'المكسيك',                   demonymAr: 'مكسيكي',           flag: '🇲🇽' },
  { code: 'FM', nameAr: 'ميكرونيزيا',                demonymAr: 'ميكرونيزي',        flag: '🇫🇲' },
  { code: 'MD', nameAr: 'مولدوفا',                   demonymAr: 'مولدوفي',          flag: '🇲🇩' },
  { code: 'MC', nameAr: 'موناكو',                    demonymAr: 'موناكي',           flag: '🇲🇨' },
  { code: 'MN', nameAr: 'منغوليا',                   demonymAr: 'منغولي',           flag: '🇲🇳' },
  { code: 'ME', nameAr: 'الجبل الأسود',              demonymAr: 'جبلي أسود',        flag: '🇲🇪' },
  { code: 'MA', nameAr: 'المغرب',                    demonymAr: 'مغربي',            flag: '🇲🇦' },
  { code: 'MZ', nameAr: 'موزمبيق',                   demonymAr: 'موزمبيقي',         flag: '🇲🇿' },
  { code: 'MM', nameAr: 'ميانمار',                   demonymAr: 'ميانماري',         flag: '🇲🇲' },
  { code: 'NA', nameAr: 'ناميبيا',                   demonymAr: 'ناميبي',           flag: '🇳🇦' },
  { code: 'NR', nameAr: 'ناورو',                     demonymAr: 'ناوري',            flag: '🇳🇷' },
  { code: 'NP', nameAr: 'نيبال',                     demonymAr: 'نيبالي',           flag: '🇳🇵' },
  { code: 'NL', nameAr: 'هولندا',                    demonymAr: 'هولندي',           flag: '🇳🇱' },
  { code: 'NZ', nameAr: 'نيوزيلندا',                 demonymAr: 'نيوزيلندي',        flag: '🇳🇿' },
  { code: 'NI', nameAr: 'نيكاراغوا',                 demonymAr: 'نيكاراغوي',        flag: '🇳🇮' },
  { code: 'NE', nameAr: 'النيجر',                    demonymAr: 'نيجري',            flag: '🇳🇪' },
  { code: 'NG', nameAr: 'نيجيريا',                   demonymAr: 'نيجيري',           flag: '🇳🇬' },
  { code: 'MK', nameAr: 'مقدونيا الشمالية',          demonymAr: 'مقدوني',           flag: '🇲🇰' },
  { code: 'NO', nameAr: 'النرويج',                   demonymAr: 'نرويجي',           flag: '🇳🇴' },
  { code: 'OM', nameAr: 'عُمان',                     demonymAr: 'عُماني',           flag: '🇴🇲' },
  { code: 'PK', nameAr: 'باكستان',                   demonymAr: 'باكستاني',         flag: '🇵🇰' },
  { code: 'PW', nameAr: 'بالاو',                     demonymAr: 'بالاوي',           flag: '🇵🇼' },
  { code: 'PS', nameAr: 'فلسطين',                    demonymAr: 'فلسطيني',          flag: '🇵🇸' },
  { code: 'PA', nameAr: 'بنما',                      demonymAr: 'بنمي',             flag: '🇵🇦' },
  { code: 'PG', nameAr: 'بابوا غينيا الجديدة',       demonymAr: 'بابوي',            flag: '🇵🇬' },
  { code: 'PY', nameAr: 'باراغواي',                  demonymAr: 'باراغواي',         flag: '🇵🇾' },
  { code: 'PE', nameAr: 'بيرو',                      demonymAr: 'بيروي',            flag: '🇵🇪' },
  { code: 'PH', nameAr: 'الفلبين',                   demonymAr: 'فلبيني',           flag: '🇵🇭' },
  { code: 'PL', nameAr: 'بولندا',                    demonymAr: 'بولندي',           flag: '🇵🇱' },
  { code: 'PT', nameAr: 'البرتغال',                  demonymAr: 'برتغالي',          flag: '🇵🇹' },
  { code: 'QA', nameAr: 'قطر',                       demonymAr: 'قطري',             flag: '🇶🇦' },
  { code: 'RO', nameAr: 'رومانيا',                   demonymAr: 'روماني',           flag: '🇷🇴' },
  { code: 'RU', nameAr: 'روسيا',                     demonymAr: 'روسي',             flag: '🇷🇺' },
  { code: 'RW', nameAr: 'رواندا',                    demonymAr: 'رواندي',           flag: '🇷🇼' },
  { code: 'KN', nameAr: 'سانت كيتس ونيفيس',          demonymAr: 'كيتسي',            flag: '🇰🇳' },
  { code: 'LC', nameAr: 'سانت لوسيا',                demonymAr: 'لوسي',             flag: '🇱🇨' },
  { code: 'VC', nameAr: 'سانت فنسنت وجزر غرينادين',  demonymAr: 'فنسنتي',           flag: '🇻🇨' },
  { code: 'WS', nameAr: 'ساموا',                     demonymAr: 'ساموي',            flag: '🇼🇸' },
  { code: 'SM', nameAr: 'سان مارينو',                demonymAr: 'سان ماريني',       flag: '🇸🇲' },
  { code: 'ST', nameAr: 'ساو تومي وبرينسيب',         demonymAr: 'ساو تومي',         flag: '🇸🇹' },
  { code: 'SA', nameAr: 'المملكة العربية السعودية',  demonymAr: 'سعودي',            flag: '🇸🇦' },
  { code: 'SN', nameAr: 'السنغال',                   demonymAr: 'سنغالي',           flag: '🇸🇳' },
  { code: 'RS', nameAr: 'صربيا',                     demonymAr: 'صربي',             flag: '🇷🇸' },
  { code: 'SC', nameAr: 'سيشيل',                     demonymAr: 'سيشيلي',           flag: '🇸🇨' },
  { code: 'SL', nameAr: 'سيراليون',                  demonymAr: 'سيرالئوني',        flag: '🇸🇱' },
  { code: 'SG', nameAr: 'سنغافورة',                  demonymAr: 'سنغافوري',         flag: '🇸🇬' },
  { code: 'SK', nameAr: 'سلوفاكيا',                  demonymAr: 'سلوفاكي',          flag: '🇸🇰' },
  { code: 'SI', nameAr: 'سلوفينيا',                  demonymAr: 'سلوفيني',          flag: '🇸🇮' },
  { code: 'SB', nameAr: 'جزر سليمان',                demonymAr: 'سليماني',          flag: '🇸🇧' },
  { code: 'SO', nameAr: 'الصومال',                   demonymAr: 'صومالي',           flag: '🇸🇴' },
  { code: 'ZA', nameAr: 'جنوب أفريقيا',              demonymAr: 'جنوب أفريقي',      flag: '🇿🇦' },
  { code: 'SS', nameAr: 'جنوب السودان',              demonymAr: 'جنوب سوداني',      flag: '🇸🇸' },
  { code: 'ES', nameAr: 'إسبانيا',                   demonymAr: 'إسباني',           flag: '🇪🇸' },
  { code: 'LK', nameAr: 'سريلانكا',                  demonymAr: 'سريلانكي',         flag: '🇱🇰' },
  { code: 'SD', nameAr: 'السودان',                   demonymAr: 'سوداني',           flag: '🇸🇩' },
  { code: 'SR', nameAr: 'سورينام',                   demonymAr: 'سورينامي',         flag: '🇸🇷' },
  { code: 'SE', nameAr: 'السويد',                    demonymAr: 'سويدي',            flag: '🇸🇪' },
  { code: 'CH', nameAr: 'سويسرا',                    demonymAr: 'سويسري',           flag: '🇨🇭' },
  { code: 'SY', nameAr: 'سوريا',                     demonymAr: 'سوري',             flag: '🇸🇾' },
  { code: 'TW', nameAr: 'تايوان',                    demonymAr: 'تايواني',          flag: '🇹🇼' },
  { code: 'TJ', nameAr: 'طاجيكستان',                 demonymAr: 'طاجيكي',           flag: '🇹🇯' },
  { code: 'TZ', nameAr: 'تنزانيا',                   demonymAr: 'تنزاني',           flag: '🇹🇿' },
  { code: 'TH', nameAr: 'تايلاند',                   demonymAr: 'تايلاندي',         flag: '🇹🇭' },
  { code: 'TL', nameAr: 'تيمور الشرقية',             demonymAr: 'تيموري',           flag: '🇹🇱' },
  { code: 'TG', nameAr: 'توغو',                      demonymAr: 'توغولي',           flag: '🇹🇬' },
  { code: 'TO', nameAr: 'تونغا',                     demonymAr: 'تونغي',            flag: '🇹🇴' },
  { code: 'TT', nameAr: 'ترينيداد وتوباغو',          demonymAr: 'ترينيدادي',        flag: '🇹🇹' },
  { code: 'TN', nameAr: 'تونس',                      demonymAr: 'تونسي',            flag: '🇹🇳' },
  { code: 'TR', nameAr: 'تركيا',                     demonymAr: 'تركي',             flag: '🇹🇷' },
  { code: 'TM', nameAr: 'تركمانستان',                demonymAr: 'تركماني',          flag: '🇹🇲' },
  { code: 'TV', nameAr: 'توفالو',                    demonymAr: 'توفالي',           flag: '🇹🇻' },
  { code: 'UG', nameAr: 'أوغندا',                    demonymAr: 'أوغندي',           flag: '🇺🇬' },
  { code: 'UA', nameAr: 'أوكرانيا',                  demonymAr: 'أوكراني',          flag: '🇺🇦' },
  { code: 'AE', nameAr: 'الإمارات العربية المتحدة',  demonymAr: 'إماراتي',          flag: '🇦🇪' },
  { code: 'GB', nameAr: 'المملكة المتحدة',           demonymAr: 'بريطاني',          flag: '🇬🇧' },
  { code: 'US', nameAr: 'الولايات المتحدة الأمريكية',demonymAr: 'أمريكي',           flag: '🇺🇸' },
  { code: 'UY', nameAr: 'أوروغواي',                  demonymAr: 'أوروغواي',         flag: '🇺🇾' },
  { code: 'UZ', nameAr: 'أوزبكستان',                 demonymAr: 'أوزبكي',           flag: '🇺🇿' },
  { code: 'VU', nameAr: 'فانواتو',                   demonymAr: 'فانواتي',          flag: '🇻🇺' },
  { code: 'VE', nameAr: 'فنزويلا',                   demonymAr: 'فنزويلي',          flag: '🇻🇪' },
  { code: 'VN', nameAr: 'فيتنام',                    demonymAr: 'فيتنامي',          flag: '🇻🇳' },
  { code: 'YE', nameAr: 'اليمن',                     demonymAr: 'يمني',             flag: '🇾🇪' },
  { code: 'ZM', nameAr: 'زامبيا',                    demonymAr: 'زامبي',            flag: '🇿🇲' },
  { code: 'ZW', nameAr: 'زيمبابوي',                  demonymAr: 'زيمبابوي',         flag: '🇿🇼' },
];

/** مرتبة أبجدياً بالعربية */
export const NATIONALITIES_SORTED = [...NATIONALITIES].sort((a, b) =>
  a.nameAr.localeCompare(b.nameAr, 'ar'),
);

/** بحث في اسم الدولة أو الجنسية */
export function searchNationalities(query: string): Nationality[] {
  const q = query.trim().toLowerCase();
  if (!q) return NATIONALITIES_SORTED;
  return NATIONALITIES_SORTED.filter(
    n =>
      n.nameAr.includes(q) ||
      n.demonymAr.includes(q) ||
      n.code.toLowerCase().includes(q),
  );
}
